### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Formatter'

### ISSUE THREAD

**Issue by kobikal1** [exoscale/python-logstash-formatter#35]
With the trival following:
```
import logging
from logstash_formatter import LogstashFormatterV1

logger = logging.getLogger()
handler = logging.StreamHandler()
formatter = LogstashFormatterV1()

handler.setFormatter(formatter)
logger.addHandler(handler)
```

I get the following traceback:

```Traceback (most recent call last):
  File "/Users/kobikalif/projects/logging_tests/logstash.py", line 2, in <module>
    from logstash_formatter import LogstashFormatterV1
  File "/Users/kobikalif/.virtualenvs/logging_tests/lib/python2.7/site-packages/logstash_formatter/__init__.py", line 22, in <module>
    class LogstashFormatter(logging.Formatter):
AttributeError: 'module' object has no attribute 'Formatter'```

**Comment by kobikal1** [comment]
It was my bug, naming the file with with logstash string.

**Comment by viewn** [comment]
Sorry. How to fix this issue? @kobika1
