### ISSUE TITLE
Catching exceptions with logger.exception and 'exceptions.Exception" has not attribute 'format'

### ISSUE THREAD

**Issue by FrEaKmAn** [exoscale/python-logstash-formatter#36]
Hi

If I do this

``` python
try:
    raise Exception()
except Exception, ex:
    logger.exception(ex)
```
I get 

``` python
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 851, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 724, in format
    return fmt.format(record)
  File "C:\Python27\lib\site-packages\logstash_formatter\__init__.py", line 142,
 in format
    msg = msg.format(**fields)
AttributeError: 'exceptions.Exception' object has no attribute 'format'
Logged from file testlogger.py, line 18
```

should I rather use logger.error() with exc_info=True?

**Comment by brutasse** [comment]
@FrEaKmAn Yes, the first parameter is supposed to be a message string. Passing `exc_info=True` is the way to go.
